name: CI/CD
on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  
jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Init Bun
        uses: oven-sh/setup-bun@v1.2.1
        with:
          bun-version: latest
          
      - name: Install Dependencies
        run: bun install
      - name: Build Windows
        run: bun run build-win
      - uses: actions/upload-artifact@v4
        with:
          name: wuwa-tweaks.exe
          path: dist/
      - name: Build Linux
        run: bun run build-linux
      - uses: actions/upload-artifact@v4
        with:
          name: wuwa-tweaks-linux
          path: dist/
      - name: Build Mac
        run: bun run build-mac
      - uses: actions/upload-artifact@v4
        with:
          name: wuwa-tweaks-mac
          path: dist/
        
      - name: Upload to Releases
        uses: dothq/tag-and-release-and-upload@v1.0.2
        with:
          version: ${{ github.ref_name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          assets: '["dist/wuwa-tweaks.exe", "dist/wuwa-tweaks-linux", "dist/wuwa-tweaks-mac"]'
          overwrite: true
            
        
      

      
          
          
      
            
