name: CI/CD
on:
  push:
    tags:
      - latest
      - 'v*'
    branches:
      - main
jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Init Bun
        uses: oven-sh/setup-bun@v1.2.1
        with:
          bun-version: latest
          
      - name: Install Dependencies
        run: bun install
      - name: Build Windows
        run: bun run build-win
      - name: Build Linux
        run: bun run build-linux
      - name: Build Mac
        run: bun run build-mac
      - name: Upload to Releases
        uses: d1ceward/draft-assets-release-action@v2.1.0
        with:
          token: ${secrets.GITHUB_TOKEN}
          files: |
            wuwa-tweaks.exe
            wuwa-tweaks-linux
            wuwa-tweaks-mac
            
        
      

      
          
          
      
            
